const records=window.AIRPORT_DATA.records||{};
const areaColors={JEN:"#156082",UKW:"#78206E",BYP:"#D6B800",RDR:"#8B3A3A",DAL:"#E97132",CQY:"#3B7D23",...(window.AIRPORT_DATA.area_colors||{})};
const AMBER="#ffd166",WHITE="#ffffff",MUTED="#6b7c89";
const MAP_MIN_LAT=29.0,MAP_MAX_LAT=37.4,MAP_MIN_LON=-104.0,MAP_MAX_LON=-91.3;
const ZFW_VISUAL_OUTLINE=[[0.305,0.150],[0.450,0.150],[0.495,0.125],[0.520,0.205],[0.575,0.205],[0.615,0.175],[0.655,0.150],[0.690,0.170],[0.735,0.220],[0.735,0.300],[0.750,0.360],[0.735,0.420],[0.765,0.470],[0.810,0.500],[0.850,0.505],[0.875,0.540],[0.885,0.585],[0.925,0.645],[0.960,0.700],[0.980,0.780],[0.950,0.835],[0.875,0.855],[0.850,0.930],[0.735,0.955],[0.715,0.990],[0.620,0.970],[0.555,0.995],[0.515,0.965],[0.440,0.970],[0.405,0.930],[0.320,0.900],[0.260,0.855],[0.205,0.820],[0.145,0.740],[0.105,0.705],[0.085,0.655],[0.085,0.560],[0.105,0.505],[0.115,0.445],[0.150,0.395],[0.205,0.355],[0.255,0.355],[0.285,0.300],[0.305,0.230],[0.305,0.150]];
let clearTimer=null,currentMarker=null;
const input=document.getElementById("airportInput"),statusEl=document.getElementById("status");
const els={sector:document.getElementById("sector"),area:document.getElementById("area"),approach:document.getElementById("approach"),vscs:document.getElementById("vscs"),contact:document.getElementById("contact"),hours:document.getElementById("hours"),airportName:document.getElementById("airportName")};
const cards={sector:document.getElementById("sectorCard"),area:document.getElementById("areaCard"),approach:document.getElementById("approachCard"),vscs:document.getElementById("vscsCard"),contact:document.getElementById("contactCard"),hours:document.getElementById("hoursCard"),airportName:document.getElementById("airportNameCard")};
function normalizeSearch(v){const s=(v||"").trim().toUpperCase();return(s.length===3&&/^[A-Z]+$/.test(s))?"K"+s:s}
function splitLines(items){return(!items||!items.length)?"":items.filter(Boolean).join("\n")}
function parseHours(hours){const h=(hours||"").trim().toUpperCase();const times=[...h.matchAll(/(\d{4})-(\d{4})/g)].map(m=>[m[1],m[2]]);if(!times.length)return[];let d="ALL";if(h.includes("M-F"))d="M-F";else if(h.includes("SU")&&h.indexOf("SU")<h.indexOf(times[0][0]))d="SU";const w=[[d,times[0][0],times[0][1]]];if(times.length>1)w.push([h.includes("SU")?"SU":"ALL",times[1][0],times[1][1]]);return w}
function militaryToMinutes(t){const h=Number(t.slice(0,2)),m=Number(t.slice(2));return h===24?1440:h*60+m}
function dayAllowed(d,n){const x=n.getDay();if(d==="ALL")return true;if(d==="M-F")return x>=1&&x<=5;if(d==="SU")return x===0;return true}
function isOpen(hours){const w=parseHours(hours);if(!w.length)return false;const n=new Date(),cur=n.getHours()*60+n.getMinutes();return w.some(([d,s,e])=>{if(!dayAllowed(d,n))return false;const sm=militaryToMinutes(s),em=militaryToMinutes(e);return em>=sm?(cur>=sm&&cur<=em):(cur>=sm||cur<=em)})}
function setText(id,v){els[id].textContent=v||"—"}
function clearClasses(){Object.values(cards).forEach(c=>{c.classList.remove("primary");c.style.background="";c.style.borderColor="";c.style.boxShadow=""});Object.values(els).forEach(e=>{e.classList.remove("red-text","green-text","amber-text","cyan-text");e.style.color=""})}
function updateZuluClock(){document.getElementById("zuluClock").textContent=new Date().toISOString().slice(11,19)+"Z"}
function scheduleClear(){if(clearTimer)clearTimeout(clearTimer);clearTimer=setTimeout(()=>{input.value="";input.focus()},1000)}
function updateResults(){const raw=input.value,upper=raw.toUpperCase();if(raw!==upper)input.value=upper;const query=normalizeSearch(upper);if(!query)return;const rec=records[query];if(!rec){statusEl.textContent=`NO MATCH: ${upper}`;statusEl.style.color="var(--red)";return}clearClasses();const sectors=rec.sectors||[],areas=rec.areas||[],apps=rec.apps||[],vscs=rec.vscs||[],contacts=rec.contacts||[],hours=rec.hours||[];const appIsOpen=apps.length>0&&isOpen(hours[0]||"");let sectorValue=splitLines(sectors);if(appIsOpen&&sectorValue)sectorValue+="\nAPP OPEN";let vscsValue="",contactValue="";if(apps.length){vscsValue=appIsOpen?splitLines(vscs):"CLOSED";contactValue=appIsOpen?splitLines(contacts):"CLOSED"}setText("sector",sectorValue);setText("area",splitLines(areas));setText("approach",splitLines(apps));setText("vscs",vscsValue);setText("contact",contactValue);setText("hours",splitLines(hours));setText("airportName",rec.airport_name||"Name not found");els.airportName.classList.add("cyan-text");if(areas.length){const a=areas[0],color=areaColors[a]||"#17212b";cards.area.style.background=color;cards.area.style.borderColor=color;els.area.style.color=a==="BYP"?"#111111":"#ffffff"}if(apps.length&&appIsOpen){cards.vscs.classList.add("primary");cards.contact.classList.add("primary");els.vscs.classList.add("green-text");els.contact.classList.add("green-text");if(sectorValue.includes("APP OPEN"))els.sector.classList.add("red-text");statusEl.textContent=`APP OPEN | ${query}`;statusEl.style.color="var(--green)"}else{if(sectors.length)cards.sector.classList.add("primary");els.sector.classList.add("amber-text");if(vscsValue==="CLOSED")els.vscs.classList.add("red-text");if(contactValue==="CLOSED")els.contact.classList.add("red-text");if(apps.length){statusEl.textContent=`APP CLOSED | ${query}`;statusEl.style.color="var(--red)"}else{statusEl.textContent=`SECTOR ONLY | ${query}`;statusEl.style.color="var(--amber)"}}currentMarker={ident:query,lat:rec.lat,lon:rec.lon};drawMap();scheduleClear()}
function drawMap(){const canvas=document.getElementById("zfwMap"),ctx=canvas.getContext("2d"),rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=Math.floor(rect.width*dpr);canvas.height=Math.floor(rect.height*dpr);ctx.scale(dpr,dpr);const w=rect.width,h=rect.height,padX=18,padY=12,uw=w-padX*2,uh=h-padY*2,sx=n=>padX+n*uw,sy=n=>padY+n*uh;ctx.fillStyle="#0f1720";ctx.fillRect(0,0,w,h);ctx.beginPath();ZFW_VISUAL_OUTLINE.forEach(([nx,ny],i)=>{const x=sx(nx),y=sy(ny);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.closePath();ctx.fillStyle="#102a36";ctx.strokeStyle="#2d5f87";ctx.lineWidth=7;ctx.fill();ctx.stroke();ctx.strokeStyle="#7fb3e6";ctx.lineWidth=3;ctx.stroke();if(currentMarker&&currentMarker.lat!=null&&currentMarker.lon!=null){const xn=(currentMarker.lon-MAP_MIN_LON)/(MAP_MAX_LON-MAP_MIN_LON),yn=(MAP_MAX_LAT-currentMarker.lat)/(MAP_MAX_LAT-MAP_MIN_LAT),x=sx(Math.max(0,Math.min(1,xn))),y=sy(Math.max(0,Math.min(1,yn)));ctx.beginPath();ctx.arc(x,y,9,0,Math.PI*2);ctx.fillStyle=AMBER;ctx.fill();ctx.lineWidth=2;ctx.strokeStyle=WHITE;ctx.stroke();ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fillStyle=WHITE;ctx.fill();ctx.fillStyle=AMBER;ctx.font="bold 13px Consolas";ctx.fillText(currentMarker.ident,x+15,y-11)}else{ctx.fillStyle=MUTED;ctx.font="bold 13px Segoe UI";ctx.textAlign="center";ctx.fillText("NO AIRPORT SELECTED",w/2,h/2);ctx.textAlign="start"}}
input.addEventListener("input",updateResults);input.addEventListener("keydown",e=>{if(e.key==="Enter"){updateResults();input.select();e.preventDefault()}});window.addEventListener("resize",drawMap);setInterval(updateZuluClock,1000);updateZuluClock();statusEl.textContent=`${Object.keys(records).length} AIRPORTS LOADED`;drawMap();input.focus();
