// Adjacent ARTCC airport clearance delivery lookup.
// Airport records are generated by the NASR workflow into window.ZFW_ADJACENT_ARTCC_AIRPORTS.airports.
window.ZFW_ADJACENT_ARTCC_AIRPORTS = {
  centers: {
    ZHU: { name: "Houston ARTCC", fdcd: "281-230-5622" },
    ZAB: { name: "Albuquerque ARTCC", fdcd: "505-856-4561" },
    ZKC: { name: "Kansas City ARTCC", fdcd: "913-254-8508" },
    ZME: { name: "Memphis ARTCC", fdcd: "901-368-8453/8449" }
  },
  airports: {}
};
